/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpubRouteImport } from './routes/epub'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as P5RouteImport } from './routes/p5'
import { Route as PunchcardRouteImport } from './routes/punchcard'
import { Route as RunningRouteImport } from './routes/running'
import { Route as StravaRouteImport } from './routes/strava'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as HyperlinksIndexRouteImport } from './routes/hyperlinks/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubRoute = EpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const P5Route = P5RouteImport.update({
  id: '/p5',
  path: '/p5',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchcardRoute = PunchcardRouteImport.update({
  id: '/punchcard',
  path: '/punchcard',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaRoute = StravaRouteImport.update({
  id: '/strava',
  path: '/strava',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperlinksIndexRoute = HyperlinksIndexRouteImport.update({
  id: '/hyperlinks/',
  path: '/hyperlinks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/hardware': typeof HardwareRoute
  '/models': typeof ModelsRoute
  '/p5': typeof P5Route
  '/punchcard': typeof PunchcardRoute
  '/running': typeof RunningRoute
  '/strava': typeof StravaRoute
  '/vocabulary': typeof VocabularyRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/hyperlinks/': typeof HyperlinksIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/hardware': typeof HardwareRoute
  '/models': typeof ModelsRoute
  '/p5': typeof P5Route
  '/punchcard': typeof PunchcardRoute
  '/running': typeof RunningRoute
  '/strava': typeof StravaRoute
  '/vocabulary': typeof VocabularyRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/hyperlinks': typeof HyperlinksIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/hardware': typeof HardwareRoute
  '/models': typeof ModelsRoute
  '/p5': typeof P5Route
  '/punchcard': typeof PunchcardRoute
  '/running': typeof RunningRoute
  '/strava': typeof StravaRoute
  '/vocabulary': typeof VocabularyRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/hyperlinks/': typeof HyperlinksIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epub'
    | '/hardware'
    | '/models'
    | '/p5'
    | '/punchcard'
    | '/running'
    | '/strava'
    | '/vocabulary'
    | '/posts/$slug'
    | '/hyperlinks/'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epub'
    | '/hardware'
    | '/models'
    | '/p5'
    | '/punchcard'
    | '/running'
    | '/strava'
    | '/vocabulary'
    | '/posts/$slug'
    | '/hyperlinks'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/epub'
    | '/hardware'
    | '/models'
    | '/p5'
    | '/punchcard'
    | '/running'
    | '/strava'
    | '/vocabulary'
    | '/posts/$slug'
    | '/hyperlinks/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpubRoute: typeof EpubRoute
  HardwareRoute: typeof HardwareRoute
  ModelsRoute: typeof ModelsRoute
  P5Route: typeof P5Route
  PunchcardRoute: typeof PunchcardRoute
  RunningRoute: typeof RunningRoute
  StravaRoute: typeof StravaRoute
  VocabularyRoute: typeof VocabularyRoute
  PostsSlugRoute: typeof PostsSlugRoute
  HyperlinksIndexRoute: typeof HyperlinksIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub': {
      id: '/epub'
      path: '/epub'
      fullPath: '/epub'
      preLoaderRoute: typeof EpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p5': {
      id: '/p5'
      path: '/p5'
      fullPath: '/p5'
      preLoaderRoute: typeof P5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punchcard': {
      id: '/punchcard'
      path: '/punchcard'
      fullPath: '/punchcard'
      preLoaderRoute: typeof PunchcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava': {
      id: '/strava'
      path: '/strava'
      fullPath: '/strava'
      preLoaderRoute: typeof StravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperlinks/': {
      id: '/hyperlinks/'
      path: '/hyperlinks'
      fullPath: '/hyperlinks/'
      preLoaderRoute: typeof HyperlinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpubRoute: EpubRoute,
  HardwareRoute: HardwareRoute,
  ModelsRoute: ModelsRoute,
  P5Route: P5Route,
  PunchcardRoute: PunchcardRoute,
  RunningRoute: RunningRoute,
  StravaRoute: StravaRoute,
  VocabularyRoute: VocabularyRoute,
  PostsSlugRoute: PostsSlugRoute,
  HyperlinksIndexRoute: HyperlinksIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
